export type CounselingProductType = {
  id: string;
  name: string;
  slug: string;
  image: string | null;
  notes: string | null;
  description: string | null;
  created_at: string;
  updated_at: string;
  products: {
    id: string;
    name: string;
    slug: string;
    image: string | null;
    with_screening: number;
    with_emergency: number;
    tag: string | null;
    default_share_profit: number | null;
    screening_modul: string | null;
    notes: string | null;
    description: string | null;
    is_counseling_general: boolean;
    created_at: string;
    updated_at: string;
    pricings: {
      id: string;
      name: string;
      year_of_experience: string;
      productable_type: string;
      productable_id: string;
      notes: string | null;
      chat_min_price: number;
      chat_max_price: number;
      video_call_min_price: number;
      video_call_max_price: number;
      face2face_min_price: number;
      face2face_max_price: number;
      default_share_profit: number;
      created_at: string;
      updated_at: string;
    }[];
  }[];
};
